# Generated by Django 4.1.5 on 2023-01-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_in_future', models.DateTimeField()),
                ('time_expired', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_planned_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
