# Generated by Django 4.1.5 on 2023-01-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_time_task_date_completion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expiration_date',
        ),
    ]
